version: "3.9"

services:
  mtg-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtg-scraper
    restart: unless-stopped
    ports:
      - "127.0.0.1:5050:5000"
    volumes:
      - ./output:/app/output
    env_file:
      - .env.prod
    environment:
      - FLASK_DEBUG=0
    command: gunicorn -b 0.0.0.0:5000 mtg_scraper_ui.app:app
